[package]
name = "uq"
version = "0.1.3"
edition = "2024"
description = "Lightning-fast macOS quarantine remover & background watcher"

[[bin]]
name = "uq"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
xattr = "1.4"
walkdir = "2.5"
notify = "8.0"
colored = "2.1"
dirs = "5.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
